Feature: implement upgrading and promoting weapons
WeedwackerPS/Weedwacker pull request #24
Opened 2022-12-23 13:19 UTC by 24karatt

ore refund on excess XP yet to be implemented

2022-12-23 15:49 UTC, akatatsu27 requested changes
The functionality is there, which is praiseworthy in itself, but the underlying code is messy and doesn't follow the layout and organization of the rest of the codebase. Too much code was added to InventoryManager.cs, which is only relevant to WeaponTab.cs. Major refactoring is needed.

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/InventoryManager.cs
> +        public async Task<bool> promoteWeaponAsync(ulong targetWeaponGuid)
This function should be a simple delegate to the actual PromoteWeaponAsync function in the WeaponTab.
The WeaponTab has pointers both to Owner and to InventoryManager, so it can still call `Owner.SendPacketAsync` and `PayPromoteCostAsync`

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/InventoryManager.cs
> +                await Owner.SendPacketAsync(new PacketWeaponUpgradeRsp(weapon, oldLevel, leftoverOres));
Not here. Only in the Req handler
```suggestion
```

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/InventoryManager.cs
> +        public async Task upgradeWeaponAsync(ulong guid, List<ulong> foodWeaponGuidList, List<ItemParam> itemParamList)
This function, as well as PromoteWeaponAsync should be delegated to the WeaponTab. Additionally, The function signature should be made more generic:
```suggestion
        public async Task UpgradeWeaponAsync(ulong guid, IEnumerable<ulong> foodWeaponGuidList, IEnumerable<ItemParam> itemParamList)
```

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Packet/Send/PacketWeaponUpgadeRsp.cs
> +        public PacketWeaponUpgradeRsp(WeaponItem item, int oldLevel, List<ItemParam> leftoverOres) : base(OpCode.WeaponUpgradeRsp)
```suggestion
        public PacketWeaponUpgradeRsp(WeaponItem item, int oldLevel, IEnumerable<ItemParam> leftoverOres) : base(OpCode.WeaponUpgradeRsp)
```

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Packet/Send/PacketWeaponPromoteRsp.cs
> +                Unk3300GGFCIPAKKDP = (uint)oldPromoteLevel,
I'll be doing a QOL pull request that updates the unknown proto fields, and fixes some linux specific issues

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Packet/Send/PacketCalcWeaponUpgradeReturnItemsRsp.cs
> +        public PacketCalcWeaponUpgradeReturnItemsRsp(ulong guid, List<ItemParam> returnItems) : base(OpCode.CalcWeaponUpgradeReturnItemsRsp)
```suggestion
        public PacketCalcWeaponUpgradeReturnItemsRsp(ulong guid, IEnumerable<ItemParam> returnItems) : base(OpCode.CalcWeaponUpgradeReturnItemsRsp)
```

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/InventoryManager.cs
> +                        if (furnitureItem.Count <= 0) await Owner.SendPacketAsync(new PacketStoreItemDelNotify(furnitureItem));
Count is explicitly disallowed from becoming negative. Additionally, when Count reaches 0, it is simply removed from the tab's item dictionary, so your `furnitureItem.Count <= 0` will always return false.
...I forgot to also remove the item from the GuidMap.
The following lines should be added to the RemoveItemAsync in the `else if (item.Count - count == 0)` case:
```
Inventory.GuidMap.Remove(item.Guid);
item.Count = 0;
```

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/InventoryManager.cs
> +        public async Task<bool> RemoveItemsByParamData(List<ItemParamData> itemDataList)
This function will still remove some items even if it ultimately returns false.
```suggestion
        public async Task<bool> RemoveItemsByParamData(IEnumerable<ItemParamData> itemDataList)
```

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/InventoryManager.cs
> +            if (await RemoveItemsByParamData(xpMats))
Weapon exp materials and relic exp materials are in the WeaponTab and RelicTab respectively, both ingame, and in this inventory system. This line defeats the purpose of sorting the items in the first place, and adds an unneccessary trip through the inventory. As mentioned above, this function should be wholly moved to the WeaponTab.

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/SubInventories/WeaponTab.cs
> +        public async Task updateWeaponAsync(WeaponItem weapon)
Updating the whole weapon object defeats the purpose of the update operation. This function is essentially equivalent to grasscutter's save function, which is terribly inefficient.
The presence of this function indicates your code doesn't try to follow the organized layout of the inventory system. Any time you call this function it's already apparent what should be updated.

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Packet/Recv/HandleWeaponPromoteReq.cs
> +            await session.Player.Inventory.promoteWeaponAsync(req.TargetWeaponGuid);
Rsp should be here

2022-12-23 15:49 UTC, akatatsu27 commented on src/GameServer/Packet/Recv/HandleWeaponUpgradeReq.cs
> +            await session.Player.Inventory.upgradeWeaponAsync(req.TargetWeaponGuid, req.FoodWeaponGuidList.ToList(), req.ItemParamList.ToList());
Rsp should be here

2022-12-23 16:12 UTC, 24karatt commented
> The functionality is there, which is praiseworthy in itself, but the underlying code is messy and doesn't follow the layout and organization of the rest of the codebase. Too much code was added to InventoryManager.cs, which is only relevant to WeaponTab.cs. Major refactoring is needed.

will do ^^ shouldn't be complicated

2022-12-23 16:29 UTC, 24karatt commented on src/GameServer/Systems/Inventory/WeaponItem.cs
> +        public bool setLevel(int level)
Is it fine to remove the protected flag from equipitem, then? As we have to change the value from outside the class.

2022-12-23 16:37 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/WeaponItem.cs
> +        public bool setLevel(int level)
you're doing it anyway through a public function, so in the end it doesn't make a difference. making the setter public has much less overhead

2022-12-27 04:30 UTC, akatatsu27 requested changes
A few small changes and it's perfect :D

2022-12-27 04:30 UTC, akatatsu27 commented on src/GameServer/Systems/Inventory/SubInventories/WeaponTab.cs
> +        public async Task updateWeaponAsync(WeaponItem weapon) //Levelups, promotes, refines all that stuff
While an improvement over the previous version, this function is still suboptimal, and not useful. `PromoteLevel` will only change in `promoteWeaponAsync` . `Level`, `Exp`, and `TotalExp` are changed only  in `upgradeWeaponAsync`. `Refinement` will of course only be changed by a yet to be implemented `RefineWeaponAsync` function.
Lastly, c# convention, which this repo follows, dictates that function and class member names start with a capital letter. if you're using visual studio, it will give you an IDE1006 warning if you hover over this function's name. To be renamed (both in InventoryManager and WeaponTab):
promoteData
upgradeWeaponAsync
promoteWeaponAsync
```suggestion
```

2022-12-27 10:03 UTC, 24karatt commented
should be good now. optionally we can remove the delegate inventorymanager functions in the handlers and access directly from the weapontab, though im not sure if theres any performance benefit to doing so

2022-12-27 15:41 UTC, akatatsu27 approved these changes

2022-12-27 15:41 UTC, merged

2022-12-27 15:47 UTC, akatatsu27 commented
> should be good now. optionally we can remove the delegate inventorymanager functions in the handlers and access directly from the weapontab, though im not sure if theres any performance benefit to doing so

accessing from the InventoryManager is more convenient and less wordy. The delegate can alternatively be written like this:
`public Task<WeaponItem> PromoteWeaponAsync(ulong targetWeaponGuid) => (SubInventories[ItemType.ITEM_WEAPON] as WeaponTab).PromoteWeaponAsync(targetWeaponGuid);`